### ISSUE TITLE
Ya no entendi

### ISSUE THREAD

**Issue by ianroses** [alejandrosalmon/progra-avanzada#1]
Que se tiene que hacer en este repo o que tiene este repo?

**Comment by alejandrosalmon** [comment]
Al menos yo practicaré con los problemas de semáforos del libro, subiré mis soluciones para que las puedan ver los demás del grupo. Si practicas semáforos y tienes soluciones a alguno de los problemas del libro subelos a su respectivo directorio que contenga el nombre del problema y tu nombre por favor. :)
